package config

const (
	REALM                 = "Realm"
	JWTSECRET             = "__jwtsecret"
	AUTHHEADER            = "__authheader"
	ADMINROLE             = "__adminrole"
	USER                  = "__user"
	ROLE                  = "__role"
	CONF_PVTKEYPATH       = "pvtkey"
	CONF_PUBLICKEYPATH    = "publickey"
	ENCODING              = "encoding"
	OBJECTTYPE_STRINGSMAP = "stringsmap"
	OBJECTTYPE_STRINGMAP  = "stringmap"
	OBJECTTYPE_MAP        = "map"
	OBJECTTYPE_STRINGARR  = "stringarray"
	OBJECTTYPE_BYTES      = "bytes"
	OBJECTTYPE_FILES      = "files"
	OBJECTTYPE_STRING     = "string"
	OBJECTTYPE_DATETIME   = "datetime"
	OBJECTTYPE_CONFIG     = "config"
	OBJECTTYPE_BOOL       = "bool"
	OBJECTTYPE_INT        = "int"
	BASEDIR               = "basedir"
	MODULEDIR             = "moduledir"
)
