package config

const (
	CONF_OBJECTLDR          = "objectloader"
	CONF_OBJECTLDR_OBJECTS  = "objects"
	CONF_OBJECTLDR_METHODS  = "methods"
	CONF_FACMGR             = "factorymanager"
	CONF_SVCMGR             = "servicemanager"
	CONF_SVCPARAMS          = "serviceparams"
	CONF_ENVIRONMENTS       = "environments"
	CONF_APP_ENVIRONMENT    = "environment"
	CONF_FILTERS            = "filters"
	CONF_APPLICATIONS       = "applications"
	CONF_APPLICATION_ENGINE = "engine"
	CONF_APPL_APPLICATION   = "application"
	CONF_CHANNEL_MGR        = "channelmanager"
	CONF_CACHE_MGR          = "cachemanager"
	CONF_TASKMGR            = "taskmanager"
	CONF_TASK_PRODUCERS     = "producers"
	CONF_TASK_CONSUMERS     = "consumers"
	CONF_TASK_RECEIVER      = "receiver"
	CONF_TASK_PROCESSOR     = "processor"
	CONF_CACHE_SVC          = "service"
	CONF_CACHE_NAME         = "cache"
	CONF_CACHE_ENC          = "encoding"
	CONF_RULESMGR           = "rulesmanager"
	CONF_APPL_OBJECT        = "object"
	CONF_APPLETS            = "applets"
	CONF_SERVER_ADDRESS     = "address"
	CONF_MESSAGING_SVC      = "messagingservice"
	CONF_MSGMGR             = "messaging"
	CONF_MESSAGE_TOPICS     = "topics"
	CONF_SECURITY           = "security"
	CONF_SECURITY_MODE      = "mode"
	CONF_SECURITY_LOCAL     = "local"
	CONF_SECURITY_REMOTE    = "remote"
	CONF_MIDDLEWARE         = "middleware"
)
