package config

const (
	CONF_OBJECTLDR          = "objectloader"
	CONF_OBJECT_NAME        = "name"
	CONF_BASE_DIR           = "basedir"
	CONF_APP_SERVER         = "server"
	CONF_OBJECTS_BASE_DIR   = "objectsbasedir"
	CONF_CONFIG_DIR         = "config"
	CONF_CONFIG_FILE        = "config.json"
	CONF_OBJECTLDR_OBJECTS  = "objects"
	CONF_OBJECTLDR_METHODS  = "methods"
	CONF_PLUGINS_FOLDER     = "plugins"
	CONF_FACTORIES          = "factories"
	CONF_SERVICES           = "services"
	CONF_SVCPARAMS          = "serviceparams"
	CONF_ENVIRONMENTS       = "environments"
	CONF_APP_ENVIRONMENT    = "environment"
	CONF_FILTERS            = "filters"
	CONF_APPLICATIONS       = "applications"
	CONF_APPLICATION_ENGINE = "engine"
	CONF_APPL_APPLICATION   = "application"
	CONF_CHANNELS           = "channels"
	CONF_CACHE              = "cache"
	CONF_TASKS              = "tasks"
	CONF_TASKS_QUEUE        = "queue"
	CONF_TASK_PRODUCER      = "producer"
	CONF_TASK_RECEIVER      = "receiver"
	CONF_TASK_PROCESSOR     = "processor"
	CONF_CACHE_SVC          = "service"
	CONF_CACHE_NAME         = "cache"
	CONF_CACHE_ENC          = "encoding"
	CONF_RULES              = "rules"
	CONF_APPL_OBJECT        = "object"
	CONF_APPLETS            = "applets"
	CONF_SERVER_ADDRESS     = "address"
	CONF_MESSAGING_SVC      = "messagingservice"
	CONF_MESSAGING          = "messaging"
	CONF_MESSAGE_TOPICS     = "topics"
	CONF_SECURITY           = "security"
	CONF_SECURITY_MODE      = "mode"
	CONF_SECURITY_LOCAL     = "local"
	CONF_SECURITY_REMOTE    = "remote"
	CONF_MIDDLEWARE         = "middleware"
)
